[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
warn_return_any = true
no_implicit_optional = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
